 export const catalogo = [
    {
      id: 1,
      marca: "Reconvexo",
      nome: "Camisa Feminina frágil como bomba",
      preco: 70,
      imagem: "Camisa-1.jpg",
      feminino: true,
    },
    {
      id: 2,
      marca: "Reconvexo",
      nome: "Camisa Ogun e Jorge",
      preco: 80,
      imagem: "Camisa-2.jpg",
      feminino: false,
    },
    {
      id: 3,
      marca: "Reconvexo",
      nome: "Camisa Ogun e Jorge Guerreiros",
      preco: 89,
      imagem: "Camisa-3.jpg",
      feminino: false,
    },
    {
      id: 4,
      marca: "Reconvexo",
      nome: "Camisa Ogun e Jorge Guerreiros",
      preco: 89,
      imagem: "Camisa-4.jpg",
      feminino:  false,
    },
    {
      id: 5,
      marca: "Reconvexo",
      nome: "Camisa Oração de São Jorge",
      preco: 89,
      imagem: "Camisa-5.jpg",
      feminino: true,
    },
    {
      id: 6,
      marca: "Reconvexo",
      nome: "Camisa Oração de São Jorge",
      preco: 89,
      imagem: "Camisa-6.jpg",
      feminino: true,
    },
    {
      id: 7,
      marca: "Reconvexo",
      nome: "Camisa Feminina Puro Deboche",
      preco: 70,
      imagem: "Camisa-7.jpg",
      feminino: true,
    },
    {
      id: 8,
      marca: "Reconvexo",
      nome: "Camisa Que Porra é Essa",
      preco: 75,
      imagem: "Camisa-8.jpg",
      feminino: false,
    },
    {
      id: 9,
      marca: "Reconvexo",
      nome: "Camisa Feminina Sereia Negra",
      preco: 89,
      imagem: "Camisa-9.jpg",
      feminino: false,
    },
    {
      id: 10,
      marca: "Reconvexo",
      nome: "Camisa Feminina Sereia Negra 2",
      preco: 89,
      imagem: "Camisa-10.jpg",
      feminino: false,
    },
    {
      id: 11,
      marca: "Reconvexo",
      nome: "Camisa Não tenho Assunto",
      preco: 75,
      imagem: "Camisa-11.jpg",
      feminino: false,
    },
    {
      id: 12,
      marca: "Reconvexo",
      nome: "Camisa Feminina Yabás",
      preco: 89,
      imagem: "Camisa-12.jpg",
      feminino: false,
    },
  ];